baseurl: /graphics-with-ggplot2-lesson
styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets
kramdown:
  parse_block_html: true
  toc_levels: 2..2
exclude:
  - '*.Rmd'
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
