# Site

title: Visualizations the ggplot Way
handouts:
  - worksheet.R
  - data/animals.csv
  - data/README.md
tag: v0.3
lesson: 2
instructor: Elizabeth Green
authors:
 - Philippe Marchand
 - Ian Carroll

# Slides

slide_sorter:
  - intro
  - layer
  - model
  - assign
  - label
  - facet
  - conclude
  - exercise

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
