# Site

title: Visualizations the ggplot Way
handouts:
  - worksheet.R
  - data/animals.csv
  - data/README.md
tag: v0.2
lesson: 4
instructor: Ian Carroll
authors:
 - Philippe Marchand
 - Ian Carroll

# Slides

slide_sorter:
  - intro
  - layer
  - model
  - assign
  - label
  - facet
  - conclude
  - solutions

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

github: [metadata]
markdown: kramdown
collections:
  - slides
